name: kaantest
favicon: null
layout_spectrum: 0.7334928186610341
typography_spectrum: 0.19063220219686627
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.55091537325643
  lightness: 0.7095188996754587
  saturation: 0.18391471169888973
  rhythmicContrast: 0.8617270598188043
purpose: []
